### ISSUE TITLE
Xbox buttons

### ISSUE THREAD

**Issue by RyanHir** [frc5431/TitanUtil#4]
The Xbox buttons are not in the correct order. Currently the only way to get proper button controls is to use button id's from the driver station instead of the TitanUtil.

**Comment by smerkousdavid** [comment]
Please make sure you are using the correct Joystick class and that the button order in Titan.java are updated. Check to see if it the index isn't shifted, and if it is, let Liav know so that he can update it. 

```
public enum Button implements ButtonZone {
            // ordered correctly, so ordinal reflects real mapping
            A, B, X, Y, BUMPER_L, BUMPER_R, BACK, START
        }
```

**Comment by liavt** [comment]
@littlekishi is right, TitanUtil somehow broke. While Java's `.ordinal()` returns a 0-indexed value, WPILib's `.getRawButton()` requires a 1-indexed value. I fixed this by simply adding a `+ 1` to the `getRawButton()` in `TitanJoystick`
